--ADD TABLE FOR CUSTOMERS WITH PRIMARY KEY 'CustomerId'
CREATE TABLE [Customers] (
  [CustomerId] INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [FirstName] NVARCHAR(255) NOT NULL,
  [LastName] NVARCHAR(255) NOT NULL
)
GO
--ADD TABLE FOR ORDERS WITH PRIMARY KEY 'Orders'
CREATE TABLE [Orders] (
  [CustomerId] INT NOT NULL,
  [OrderId] INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [OrderDateTime] DATETIME2 NOT NULL DEFAULT GETDATE(),
  [Total] MONEY NOT NULL,
  [LocationId] INT NOT NULL

)
GO
--ADD TABLE FOR ORDERDETAIL WITH PRIMARY KEY 'OrderDetail'
CREATE TABLE [OrderDetail] (
  [OrderDetailId] INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [ProductId] INT NOT NULL,
  [ProductQuantity] INT NOT NULL,
  [OrderId] INT NOT NULL
)
GO
--ADD TABLE FOR PRODUCTS WITH PRIMARY KEY 'ProductId'
CREATE TABLE [Products] (
  [Name] NVARCHAR(255) NOT NULL,
  [ProductId] INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [Price] MONEY NOT NULL
)
GO
--ADD TABLE FOR LOCATION WITH PRIMARY KEY 'LocationId'
CREATE TABLE [Location] (
  [LocationId] INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [Address] NVARCHAR(255) NOT NULL
)
GO
--ADD TABLE FOR INVENTORY WITH PRIMARY KEY 'Inventory Id'
CREATE TABLE [Inventory] (
  [InventoryId] INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [ProductId] INT NOT NULL,
  [Quantity] INT NOT NULL,
  [LocationId] INT NOT NULL
)
GO
--ADD FOREIGN KEYS
ALTER TABLE [Orders] ADD FOREIGN KEY ([CustomerId]) REFERENCES [Customers] ([CustomerId])--FOREIGN KEY 'CustomerId' FOR ORDERS
GO

ALTER TABLE [Orders] ADD FOREIGN KEY ([LocationId]) REFERENCES [Location] ([LocationId])--FOREIGN KEY 'LocationId' FOR ORDERS
GO

ALTER TABLE [OrderDetail] ADD FOREIGN KEY ([ProductId]) REFERENCES [Products] ([ProductId]) --FOREIGN KEY 'ProductId' FOR ORDERDETAILS
GO

ALTER TABLE [Inventory] ADD FOREIGN KEY ([ProductId]) REFERENCES [Products] ([ProductId]) --FOREIGN KEY 'ProductId' FOR INVENTORY
GO

ALTER TABLE [Inventory] ADD FOREIGN KEY ([LocationId]) REFERENCES [Location] ([LocationId]) -- FOREIGN KEY 'LocationId' FOR INVENTORY
GO
 
ALTER TABLE [OrderDetail] ADD FOREIGN KEY ([OrderId]) REFERENCES [Orders] ([OrderId]) -- FOREIGN KEY 'OrderId' FOR ORDERDETAIL
GO





